- hosts: app
  become: true
  gather_facts: false
  pre_tasks:
    - name: wait for container to be reachable
      wait_for_connection:
        timeout: 60
    - name: gather facts
      setup:
  tasks:
    - name: install packages
      apt:
        name:
          - git
          - openssh-server
          - curl
          - vim
          - docker.io
          - docker-compose
          - htop
        state: present
        update_cache: true

    - name: copy public key
      authorized_key:
        user: root
        key: "{{ lookup('env', 'SSH_PUBLIC_KEY') }}"
        state: present

    - name: clone repo
      git:
        repo: https://github.com/ewanchukwilliam/Live-Insider-Trading-Analytics
        dest: /app
        version: main
        force: yes

    - name: install lazydocker
      shell: |
        curl -Lo /tmp/lazydocker.tar.gz "https://github.com/jesseduffield/lazydocker/releases/download/v0.23.3/lazydocker_0.23.3_Linux_x86_64.tar.gz"
        tar -xf /tmp/lazydocker.tar.gz -C /usr/local/bin lazydocker
      args:
        creates: /usr/local/bin/lazydocker
